name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Upload blogtok.tar to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: "blogtok.tar"
          target: "/home/ec2-user"

      - name: SSH into EC2 and Deploy Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~

            if ! command -v docker &> /dev/null; then
              sudo yum update -y
              sudo yum install -y docker
              sudo service docker start
              sudo systemctl enable docker
              sudo usermod -aG docker ec2-user
            fi

            sudo docker --version

            sudo docker ps -a --filter "name=blogtok" -q | xargs -r sudo docker rm -f
            sudo lsof -ti:3000 | xargs -r sudo kill -9 || true

            sudo docker load -i blogtok.tar
            sudo docker run -d -p 3000:3000 --name blogtok blogtok
