name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and Deploy Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~

            # Check if Docker is installed, if not, install it
            if ! command -v docker &> /dev/null; then
              sudo yum update -y
              sudo yum install -y docker
              sudo service docker start
              sudo systemctl enable docker
              sudo usermod -aG docker ec2-user
            fi

            # Verify Docker version
            sudo docker --version

            # Stop and remove any existing container named 'blogtok'
            sudo docker ps -a --filter "name=blogtok" -q | xargs -r sudo docker rm -f

            # Kill any process running on port 3000 (if any)
            sudo lsof -ti:3000 | xargs -r sudo kill -9 || true

            # Load the Docker image from the tar file
            sudo docker load -i /home/ec2-user/blogtok.tar

            # Run the new Docker container
            sudo docker run -d -p 3000:3000 --name blogtok blogtok
