name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and Deploy Docker from TAR
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user
            sudo docker stop blogtok || true
            sudo docker rm blogtok || true
            sudo docker load -i blogtok.tar
            sudo docker run -d -p 3000:3000 --name blogtok blogtok
