name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and Deploy Docker from TAR
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Navigate to the home directory
            cd /home/ec2-user
            sudo apt update
            sudo apt install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo docker --version

            # Stop and remove any container named 'blogtok' if it exists
            sudo docker ps -a --filter "name=blogtok" -q | xargs -r sudo docker rm -f
            # Check if the container is still running and remove it if bound to port 3000
            sudo docker ps -a --filter "publish=3000" -q | xargs -r sudo docker stop || true
            sudo docker ps -a --filter "publish=3000" -q | xargs -r sudo docker rm -f

            # Load the Docker image from the tar file
            sudo docker load -i blogtok.tar

            # Run the new Docker container
            sudo docker run -d -p 3000:3000 --name blogtok blogtok
