name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and Deploy Docker from TAR
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Go to the home directory
            cd ~

            # Install Docker if not already installed
            if ! command -v docker &> /dev/null
            then
              echo "Docker not found. Installing..."
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker $USER
            fi

            # Show Docker version
            docker --version

            # Clean up old container if exists
            sudo docker ps -a --filter "name=blogtok" -q | xargs -r sudo docker rm -f

            # Free up port 3000 if needed
            sudo lsof -ti:3000 | xargs -r sudo kill -9

            # Load Docker image from tar
            sudo docker load -i blogtok.tar

            # Run the container
            sudo docker run -d -p 3000:3000 --name blogtok blogtok
