name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and Deploy Docker from TAR
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~

            # Install Docker for Amazon Linux
            if ! command -v docker &> /dev/null; then
              echo "Installing Docker on Amazon Linux..."
              sudo yum update -y
              sudo yum install -y docker
              sudo service docker start
              sudo systemctl enable docker
              sudo usermod -aG docker ec2-user
            fi

            # Show Docker version
            sudo docker --version

            # Remove old container if exists
            sudo docker ps -a --filter "name=blogtok" -q | xargs -r sudo docker rm -f

            # Free up port 3000 if needed
            sudo lsof -ti:3000 | xargs -r sudo kill -9 || true

            # Load the Docker image
            sudo docker load -i blogtok.tar

            # Run the container
            sudo docker run -d -p 3000:3000 --name blogtok blogtok
